export const CONTENTFUL_BASE_URL = process.env.NEXT_PUBLIC_CONTENTFUL_BASE_URL
export const SPACE_ID = process.env.NEXT_PUBLIC_CONTENTFUL_SPACE_ID
export const ACCESS_TOKEN = process.env.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN
